subdomain: jamesbaker
language: en-GB
custom-domain:
  domain: jamesbaker.uk
directives:
  head-directive: |
    
  footer-directive: |
    <a class="image-link" href="https://departure.blog/pixel-bears/" target="_blank">
    <picture>
      <!-- User prefers light mode: -->
      <source srcset="https://bear-images.sfo2.cdn.digitaloceanspaces.com/jamesbaker/bear-james-baker-light.png"
      media="(prefers-color-scheme: light)"/>
      <!-- User prefers dark mode: -->
      <source srcset="https://bear-images.sfo2.cdn.digitaloceanspaces.com/jamesbaker/bear-james-baker.png" 
        media="(prefers-color-scheme: dark)">
      <!-- User has no color preference: -->
      <img src="https://bear-images.sfo2.cdn.digitaloceanspaces.com/jamesbaker/bear-james-baker-light.png"
        alt="Pixel bear"
        style="width: 96px; image-rendering: pixelated;">
    </picture>
    </a>
    
    [Get in touch](/contact/) | [Follow a feed](/feeds/)
    
    <script src="https://cdn.jsdelivr.net/gh/robertbirming/bear-plugins/gallery-lightbox.js"></script>
advanced-settings:
  collect-analytics: false
  date-format: Y-m-d
  fathom-site-id:
  blog-path: blog
  rss-alias:
  custom-meta-tag:
  robots-txt-content: |
    User-agent: *
    Disallow: /
